export interface Category {
  id: number;
  name: string;
  color: string;
  icon: string;
}

export interface SubCategory {
  categoryId: number;
  id: number;
  name: string;
}

export const CATEGORIES: Category[] = [
  { id: 1, name: "Essencial", color: "#ef4444", icon: "Heart" },
  { id: 2, name: "Segurança, Tecnologia e Suporte", color: "#3b82f6", icon: "ShieldCheck" },
  { id: 3, name: "Órgãos Públicos & Instituições", color: "#10b981", icon: "Building2" },
  { id: 4, name: "Beleza e Estética", color: "#ec4899", icon: "Sparkles" },
  { id: 5, name: "Pet Shop", color: "#f59e0b", icon: "Dog" },
  { id: 6, name: "Automotivo", color: "#6b7280", icon: "Car" },
  { id: 7, name: "Casa e Construção", color: "#8b5cf6", icon: "Home" },
  { id: 8, name: "Serviços Profissionais", color: "#06b6d4", icon: "Briefcase" },
  { id: 9, name: "Social e Comunidade", color: "#f97316", icon: "Users" },
  { id: 10, name: "Desenvolvimento Pessoal", color: "#84cc16", icon: "GraduationCap" },
  { id: 11, name: "Mobilidade Urbana", color: "#6366f1", icon: "MapPin" },
  { id: 12, name: "Comércio & Varejo", color: "#d946ef", icon: "ShoppingBag" },
];

export const SUB_CATEGORIES: SubCategory[] = [
  { categoryId: 1, id: 1000, name: "Alimentação (restaurante, lanchonete, pizzaria)" },
  { categoryId: 1, id: 1001, name: "Supermercado / Mercado" },
  { categoryId: 1, id: 1002, name: "Padaria / Açougue / Hortifruti" },
  { categoryId: 1, id: 1003, name: "Distribuidora (água, gás, bebidas)" },
  { categoryId: 1, id: 1004, name: "Farmácia" },
  { categoryId: 1, id: 1005, name: "Hospital / Clínica / UPA" },
  { categoryId: 1, id: 1006, name: "Laboratório" },
  { categoryId: 1, id: 1007, name: "Hospedagem (hotel, pousada, temporada)" },
  { categoryId: 1, id: 1008, name: "Espetinho" },
  { categoryId: 1, id: 1009, name: "Peixaria" },
  { categoryId: 1, id: 1010, name: "Sorveteria/Açaiteria" },
  { categoryId: 2, id: 2001, name: "Segurança Eletrônica / Monitoramento" },
  { categoryId: 2, id: 2002, name: "Alarmes / Câmeras" },
  { categoryId: 2, id: 2003, name: "Controle de Acesso / Portaria" },
  { categoryId: 2, id: 2004, name: "Extintores / Brigada" },
  { categoryId: 2, id: 2005, name: "Chaveiro" },
  { categoryId: 2, id: 2006, name: "Transporte Hospitalar" },
  { categoryId: 2, id: 2007, name: "Assistência Técnica (celular/informática)" },
  { categoryId: 2, id: 2008, name: "Loja de Tecnologia" },
  { categoryId: 2, id: 2009, name: "Provedor de Internet / Automação / Suporte TI" },
  { categoryId: 3, id: 3001, name: "Prefeitura / Câmara / Secretarias" },
  { categoryId: 3, id: 3002, name: "Fórum / Tribunal" },
  { categoryId: 3, id: 3003, name: "Delegacia / Polícia / Bombeiros" },
  { categoryId: 3, id: 3004, name: "Presídio / Unidade Prisional" },
  { categoryId: 3, id: 3005, name: "INSS / Receita / Órgãos Federais" },
  { categoryId: 3, id: 3006, name: "CRAS / CREAS / Conselho Tutelar" },
  { categoryId: 3, id: 3007, name: "Detran / Procon" },
  { categoryId: 4, id: 4001, name: "Salão de Beleza / Barbearia" },
  { categoryId: 4, id: 4002, name: "Estética / Harmonização" },
  { categoryId: 4, id: 4003, name: "Manicure / Pedicure" },
  { categoryId: 4, id: 4004, name: "Spa / Massagem" },
  { categoryId: 4, id: 4005, name: "Tatuagem / Piercing" },
  { categoryId: 4, id: 4006, name: "Cosméticos / Perfumaria" },
  { categoryId: 5, id: 5001, name: "Pet Shop (varejo)" },
  { categoryId: 5, id: 5002, name: "Clínica Veterinária" },
  { categoryId: 5, id: 5003, name: "Banho e Tosa" },
  { categoryId: 5, id: 5004, name: "Hotel / Creche Pet" },
  { categoryId: 5, id: 5005, name: "Serviços Pet (adestramento, cuidador)" },
  { categoryId: 6, id: 6001, name: "Oficina / Centro Automotivo" },
  { categoryId: 6, id: 6002, name: "Auto Peças / Pneus" },
  { categoryId: 6, id: 6003, name: "Funilaria / Pintura" },
  { categoryId: 6, id: 6004, name: "Lava Jato" },
  { categoryId: 6, id: 6005, name: "Posto de Combustível" },
  { categoryId: 6, id: 6006, name: "Despachante / Vistoria Veicular" },
  { categoryId: 6, id: 6007, name: "Guincho / Reboque" },
  { categoryId: 7, id: 7001, name: "Construção / Reforma" },
  { categoryId: 7, id: 7002, name: "Elétrica / Hidráulica" },
  { categoryId: 7, id: 7003, name: "Marcenaria / Serralheria / Vidraçaria" },
  { categoryId: 7, id: 7004, name: "Material de Construção / Ferragista" },
  { categoryId: 7, id: 7005, name: "Iluminação / Tintas / Pisos" },
  { categoryId: 7, id: 7006, name: "Energia Solar" },
  { categoryId: 7, id: 7007, name: "Limpeza / Dedetização / Mudança" },
  { categoryId: 7, id: 7008, name: "Decoração / Floricultura" },
  { categoryId: 8, id: 8001, name: "Advocacia" },
  { categoryId: 8, id: 8002, name: "Contabilidade / Auditoria" },
  { categoryId: 8, id: 8003, name: "Consultoria Empresarial" },
  { categoryId: 8, id: 8004, name: "Imobiliária / Corretor" },
  { categoryId: 8, id: 8005, name: "Arquitetura / Engenharia / Design" },
  { categoryId: 8, id: 8006, name: "Cartório / Documentação" },
  { categoryId: 8, id: 8007, name: "Instituições Financeiras" },
  { categoryId: 8, id: 8008, name: "Fotografia / Filmagem" },
  { categoryId: 8, id: 8009, name: "Cerimonial / Eventos" },
  { categoryId: 9, id: 9001, name: "Igrejas / Templos / Comunidades Religiosas" },
  { categoryId: 9, id: 9002, name: "ONG / Associação / Sindicato" },
  { categoryId: 9, id: 9003, name: "Centro Comunitário / Grupos" },
  { categoryId: 9, id: 9004, name: "Clube / Academia / Quadra" },
  { categoryId: 9, id: 9005, name: "Espaço Cultural / Teatro / Cinema" },
  { categoryId: 9, id: 9006, name: "Eventos / Casas de Show / Bar" },
  { categoryId: 9, id: 9007, name: "Parques" },
  { categoryId: 10, id: 1001, name: "Escola (infantil ao médio)" },
  { categoryId: 10, id: 1002, name: "Universidade / Instituto Federal" },
  { categoryId: 10, id: 1003, name: "Faculdade / Escola Técnica" },
  { categoryId: 10, id: 1004, name: "Cursos Profissionalizantes / Idiomas" },
  { categoryId: 10, id: 1005, name: "Curso Preparatório / Reforço" },
  { categoryId: 10, id: 1006, name: "Mentoria / Coaching" },
  { categoryId: 10, id: 1007, name: "Escola de Artes / Esportes" },
  { categoryId: 11, id: 1101, name: "Táxi / Motorista de Aplicativo" },
  { categoryId: 11, id: 1102, name: "Mototáxi" },
  { categoryId: 11, id: 1103, name: "Transporte Escolar / Executivo" },
  { categoryId: 11, id: 1104, name: "Transporte Público (ônibus)" },
  { categoryId: 11, id: 1105, name: "Frete / Transporte de Cargas" },
  { categoryId: 11, id: 1106, name: "Locação de Veículos / Bicicletas" },
  { categoryId: 11, id: 1107, name: "Estacionamento" },
  { categoryId: 12, id: 1201, name: "Móveis / Eletrodomésticos / Eletrônicos" },
  { categoryId: 12, id: 1202, name: "Moda (feminina, masculina, infantil, fitness)" },
  { categoryId: 12, id: 1203, name: "Calçados / Ótica / Joias" },
  { categoryId: 12, id: 1204, name: "Shopping / Loja de Departamento / Outlet" },
  { categoryId: 12, id: 1205, name: "Brinquedos / Papelaria / Livraria" },
  { categoryId: 12, id: 1206, name: "Utilidades Domésticas" },
  { categoryId: 12, id: 1207, name: "Produtos Naturais / Suplementos" },
  { categoryId: 12, id: 1208, name: "Agropecuária / Variedades" },
  { categoryId: 12, id: 1209, name: "Loja de Bebê / Infantil" },
  { categoryId: 12, id: 1210, name: "Profissional Autonomo" },
  { categoryId: 12, id: 1211, name: "Alimentos" },
];
