import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";

dotenv.config();

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;

const supabase = createClient(supabaseUrl!, supabaseServiceKey!);

async function safeSupabaseWrite(
  supabase: any,
  tableName: string,
  operation: 'insert' | 'update',
  payload: any,
  idToUpdate?: string
): Promise<{ data: any[] | null; error: any }> {
  let currentPayload = Array.isArray(payload) 
    ? payload.map((p: any) => ({ ...p }))
    : { ...payload };

  let attempts = 0;
  const maxAttempts = 8;

  while (attempts < maxAttempts) {
    attempts++;
    console.log(`\n--- Tentativa ${attempts} ---`);
    console.log("Payload keys:", Object.keys(currentPayload));
    try {
      let result;
      if (operation === 'insert') {
        const toInsert = Array.isArray(currentPayload) ? currentPayload : [currentPayload];
        result = await supabase.from(tableName).insert(toInsert).select();
      } else {
        result = await supabase.from(tableName).update(currentPayload).eq('id', idToUpdate).select();
      }

      if (!result.error) {
        console.log("✅ Sucesso!");
        return { data: result.data, error: null };
      }

      const error = result.error;
      console.log(`❌ Erro recebido (Código: ${error.code}): ${error.message}`);
      
      const isMissingColumnError = 
        error.code === '42703' || 
        error.code === 'PGRST204' || 
        (error.message && error.message.toLowerCase().includes('could not find') && error.message.toLowerCase().includes('column'));

      if (isMissingColumnError && error.message) {
        let match = error.message.match(/Could not find the '([^']+)' column/i);
        if (!match) {
          match = error.message.match(/column "([^"]+)" of relation/i);
        }
        if (!match) {
          match = error.message.match(/column '([^']+)' does not exist/i);
        }

        if (match && match[1]) {
          const columnName = match[1];
          console.warn(`[SafeSupabaseWrite] Coluna ausente detectada: '${columnName}'. Removendo do payload.`);
          
          if (Array.isArray(currentPayload)) {
            currentPayload = currentPayload.map((p: any) => {
              const newP = { ...p };
              delete newP[columnName];
              return newP;
            });
          } else {
            delete currentPayload[columnName];
          }
          continue;
        }

        console.log("⚠️ Erro de coluna ausente, mas nenhum nome de coluna foi capturado pelo regex.");
      } else {
        console.log("⚠️ Não é um erro de coluna ausente.");
      }

      return { data: null, error };

    } catch (err: any) {
      console.error(`Erro inesperado na tentativa ${attempts}:`, err);
      return { data: null, error: { message: err.message, code: err.code || 'UNEXPECTED' } };
    }
  }

  return { data: null, error: { message: "Maximum recovery retries reached.", code: "MAX_RETRIES" } };
}

async function run() {
  const { data: ests } = await supabase.from("establishments").select("*").limit(1);
  if (!ests || ests.length === 0) return;
  const est = ests[0];

  // Exact payload as generated by server.ts under admin role
  const updatePayload: any = {
    name: "Teste de Update",
    category_id: 6,
    sub_category: "Oficina",
    address: "Rua Teste",
    phone: "123",
    whatsapp: "456",
    website: "web",
    instagram_url: null,
    facebook_url: null,
    whatsapp_url: null,
    youtube_url: null,
    tiktok_url: null,
    linkedin_url: null,
    twitter_url: null,
    hours: "Sempre aberto",
    is_open_24_hours: true,
    description: "Teste",
    latitude: -11.7,
    longitude: -49.0,
    maps_link: "link",
    plus_code: "code",
    city_id: 1,
    state_id: 1,
    images: [],
    tags: '',
    is_featured: true,
    is_verified: true,
    is_premium: true,
    is_active: true,
    featured_order: null,
    featured_start: '2026-06-12T17:08:32.90458+00:00',
    featured_end: null,
    featured_type: 'normal'
  };

  const res = await safeSupabaseWrite(supabase, "establishments", "update", updatePayload, est.id);
  console.log("\nResultado final:", res);
}

run();
